application: battleship-game-1282
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /tasks/send_email_reminder
  script: main.app
  login: admin

- url: /crons/schedule_email_reminder
  script: main.app

- url: /_ah/spi/.*
  script: battleship.api
  secure: always

libraries:

- name: webapp2
  version: latest

- name: endpoints
  version: latest
